// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { envDiagnostics, getSupabaseEnvOrThrow } from '@/lib/env';

const { url: SUPABASE_URL, anonKey: SUPABASE_ANON_KEY, configured: hasSupabaseConfig } =
  getSupabaseEnvOrThrow();

if (!hasSupabaseConfig) {
  console.warn(
    `[SUPABASE] Configuración degradada. Faltantes: ${envDiagnostics.missingSupabase.join(", ")}.`,
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
